networks:
    laravel:

services:
    app:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html:delegated
            - ./dockerfiles/nginx/logs:/var/log/nginx:delegated
        depends_on:
            - php
            - redis
            - mysql
            - mailhog
        networks:
            - laravel

    mysql:
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - '4306:3306'
        volumes:
            - ./dockerfiles/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: symfony-react
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - APP_PHP_INI_PATH=${APP_PHP_INI_PATH}
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - laravel

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - laravel

    composer:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - APP_PHP_INI_PATH=${APP_PHP_INI_PATH}
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        entrypoint: ['composer']
        networks:
            - laravel

    npm:
        image: node:22
        volumes:
            - ./:/var/www/html
        ports:
            - '3000:3000'
            - '3001:3001'
            - '5173:5173'
        working_dir: /var/www/html
        networks:
            - laravel

    console:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - APP_PHP_INI_PATH=${APP_PHP_INI_PATH}
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql
        entrypoint: ['php', '/var/www/html/bin/console']
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - laravel
